
name: Live Sports Analystics & Monitoring Dashboard - CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Get dependencies
      run: go get -v -t -d ./...
    
    - name: Build
      run: go build -v ./...
    
    - name: Run tests
      run: go test ./... -v

    - name: Run additional test commands
      run: |
        go fmt ./...
        go vet ./...
        go test -race ./...
